[project]
name = "url-sho"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.2",
    "pymongo>=4.15.1",
    "pytest>=8.4.2",
    "validators>=0.35.0",
]
